[package]
name = "archiadb"
version = "0.0.2"
edition = "2024"
rust-version = "1.94"
description = "hierarchical embedded database"
repository = "https://github.com/wilgaboury/archiadb"
license = "MIT"

[lib]
name = "archiadb"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
bon = "3.9"
crossbeam = "0.8"
dashmap = "6.1.0"
function_name = "0.3.0"
io-uring = "0.7"
rustix = { version = "1.1.4", features = ["fs", "io_uring"] }
libc = "0.2"
parking_lot = "0.12.5"
tokio = { version = "1", features = ["sync"] }
thiserror = "2.0.19"
derive_more = { version = "2.1.1", features = ["full"] }
rapidhash = "4.5.1"

[dev-dependencies]
winit = { version = "0.30", features = ["x11", "wayland"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rand = "0.8"
eframe = "0.36.1"
egui_extras = "0.36.1"
palette = "0.7.7"
dioxus = { version = "0.7", features = ["desktop"] }
dioxus-desktop = "0.7"

[features]
manual = []
