#!/bin/bash

export RUST_BACKTRACE=1

if [ -z "$1" ]; then
    # Running tests in parallel causes io_uring buffer registrations errors
    cargo test -- --test-threads=1
else
    # Inspector needs to run on main thread
    cargo test "$1" -- --test-threads=1
fi